# Generated by Django 5.2.1 on 2025-05-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beverage',
            name='default_milk',
        ),
        migrations.RemoveField(
            model_name='beverage',
            name='default_powder',
        ),
        migrations.RemoveField(
            model_name='beverage',
            name='default_sugar',
        ),
        migrations.AlterField(
            model_name='beverage',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
