# Generated by Django 5.2.1 on 2025-05-22 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending', '0002_remove_beverage_default_milk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beverage',
            name='coffee_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='beverage',
            name='coffee_qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='beverage',
            name='milk_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='beverage',
            name='milk_qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='beverage',
            name='sugar_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='beverage',
            name='sugar_qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='beverage',
            name='tea_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='beverage',
            name='tea_qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='beverage',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
